Controllers/EtiketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogg.Controllers
{
    using Models;
    public class EtiketController : Controller
    {
        // GET: Etiket
        public ActionResult Index(int id)
        {
            return View(id);
        }
        public PartialViewResult EtiketlerWidget()
        {
            return PartialView(Context.Link.Etikets.ToList());
        }

        public ActionResult MakaleListele(int id)
        {
            var data = Context.Link.Makales.Where
                (x => x.Etikets.Any(y => y.EID == id)).ToList();
            return View("MakaleListeleWidget",data);
        }
    }
}

Controllers/HomeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blogg.Models;

namespace Blogg.Controllers
{
    using App_Classes;
    public class HomeeController : Controller
    {


        // GET: Homee
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MakaleListele()
        {
            var data = Context.Link.Makales.ToList();
            return View("MakaleListeleWidget", data);

        }

        public PartialViewResult PopulerMakaleler()
        {
            var model = Context.Link.Makales.OrderByDescending(x => x.EklenmeTarihi).Take(3).ToList();
            return PartialView(model);
        }

    }
}

Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogg.Controllers
{
    using Models;
    public class KategoriController : Controller
    {
        // GET: Kategori
        
        public ActionResult Index(int id)
        {

            return View(id);
        }
        public PartialViewResult KategoriWidget()
        {
            return PartialView(Context.Link.Kategoris.ToList());
        }
        public ActionResult MakaleListele(int id)
        {
            var data = Context.Link.Makales.Where(x => x.KategoriID == id).ToList();
            return View("MakaleListeleWidget", data);
        }
    }
}

Views/Homee/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section head{


}


<h2>@ViewBag.mesaj</h2>
@*@section Kategoriler{
        @{ Html.RenderAction("KategoriWidget", "Kategori");}


    }

    @section Etiketler{
        @{ Html.RenderAction("EtiketlerWidget", "Etiket");}


    }
    @section Arama{
    }
    @section PopulerMakaleler{
        @{ Html.RenderAction("PopulerMakaleler", "Homee");}

    }*@

@{
    Html.RenderAction("MakaleListele", "Homee");
    }

Views/Homee/PopulerMakaleler.cshtml
@model IEnumerable<Blogg.Models.Makale>


@helper IcerikKisalt(string metin)
{
    if (metin.Length > 99)
    {
        <span>@metin.Substring(0, 99)</span>
    }
    else
    {
        @metin
    }
}


<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
        <h3 style="color:burlywood">En Son Eklenenler</h3>
        <div class="tm-content-box">
            @foreach (Blogg.Models.Makale item in Model)
            {
                <span class="">@item.EklenmeTarihi.ToShortDateString() /</span>
                <span>
                    <a>@item.Yorums.Count</a><img src="https://img.icons8.com/ios/24/000000/quote.png">


                </span>
                <p href="/Makale/Detay/@item.MakaleID">
                    @item.Baslik
                    <a class="btn btn-success rounded" href="/Makale/Detay/@item.MakaleID">Hepsini Oku</a>
                </p>
           
                <img src="@item.Resim.KucukBoyut" alt="Image" class="img-fluid tm-img-post">

                <p>@IcerikKisalt(item.İcerik)</p>

            }
        </div>
    </div>


</div>